### ISSUE TITLE
Is it possible to extract data from text?

### ISSUE THREAD

**Issue by peterpme** [bukinoshita/sketch-json#4]
Hey, awesome module!

I'm wondering if I can extract the values for the data (and if there's any reason to do so):

![image](https://user-images.githubusercontent.com/1211905/38886707-5b3f5598-423c-11e8-9a96-061e9b0b6f2e.png)

If I search the output for "Peter". I don't get anything back. Is this by design?

Thanks!

**Comment by bukinoshita** [comment]
Yes, you can extract data from text. I'm not sure why you can't... Can you send me the sketch file?
